### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by MichielvdVelde** [unshiftio/ultron#19]
I'd like to use this module in TypeScript, but there is no definition file.

Adding a definition file involves little work and I wrote it already, so I could hack it into my project.

Would a PR for this be accepted? Or should I add a definition to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)?

Thanks in advance!

**Comment by lpinca** [comment]
@MichielvdVelde I think it's better to add it to DefinitelyTyped. We don't use TypeScript so definitions would not be maintained here.

**Comment by MichielvdVelde** [comment]
Thanks for the fast reply. I will add a definition to DefinitelyTyped soon.

**Comment by lpinca** [comment]
Thank you!
