### ISSUE TITLE
Please include a LICENSE file

### ISSUE THREAD

**Issue by tdawson** [unshiftio/ultron#4]
Several Linux distributions require a license file when packaging software, Fedora among them.
I am trying to package ultron to be included in Fedora.
Although you state that the license for Ultron is MIT, in both README.md and package.json, you do not have a copy of the license file in the code.
Could you please add a MIT license file to your souce code.

**Comment by 3rd-Eden** [comment]
@tdawson I'll update all `unshiftio/*` projects with the correct license in a bit. Thanks for raising this issue.

**Comment by tdawson** [comment]
I see it is included now.  Thank you.

**Comment by 3rd-Eden** [comment]
Your welcome, every module under this organization now contains the required license files.
