### ISSUE TITLE
Don't rely on _events, use .eventNames() instead when it's present.

### ISSUE THREAD

**Issue by ChALkeR** [unshiftio/ultron#6]
`EventEmitter.prototype.eventNames` was added in https://github.com/nodejs/node/pull/5617 an will be available in Node.js 6.0 and later.

You should probably check for its presense and use that instead of manually listing `EventEmitter.prototype._events` in [index.js#L81-L83](https://github.com/unshiftio/ultron/blob/1.0.2/index.js#L81-L83), so you won't be hitting undocumented internal API.

**Comment by lpinca** [comment]
Closing as #7 has been merged.
Thanks!
